AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
#  optionsImages:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: dist/src/
#      Handler: options.lambdaHandler
#      Runtime: nodejs10.x
#      Description : ""
#      MemorySize: 32
#      Timeout: 3
#      Role: arn:aws:iam::195957709288:role/lambda-dynamodb-access
#      Events:
#        Api:
#          Type: Api
#          Properties:
#            Path: /images
#            Method: OPTIONS
  postImage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/
      Handler: postImage.lambdaHandler
      Runtime: nodejs10.x
      Description : ""
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::195957709288:role/lambda-dynamodb-access
      Environment:
        Variables: 
          BUCKET_NAME: jabara-serverless-app-photos
          TABLE_NAME : photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: POST
  updateImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/
      Handler: updateImage.lambdaHandler
      Runtime: nodejs10.x
      Description : ""
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::195957709288:role/lambda-dynamodb-access
      Environment:
        Variables: 
          BUCKET_NAME: jabara-serverless-app-photos
          TABLE_NAME : photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: PUT
  getImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/
      Handler: getImages.lambdaHandler
      Runtime: nodejs10.x
      Description : ""
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::195957709288:role/lambda-dynamodb-access
      Environment:
        Variables: 
          BUCKET_NAME: jabara-serverless-app-photos
          TABLE_NAME : photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: GET
#  optionsImageById:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: dist/src/
#      Handler: options.lambdaHandler
#      Runtime: nodejs10.x
#      Description : ""
#      MemorySize: 32
#      Timeout: 3
#      Role: arn:aws:iam::195957709288:role/lambda-dynamodb-access
#      Events:
#        Api:
#          Type: Api
#          Properties:
#            Path: /image/{id}
#            Method: OPTIONS
  getImageById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/
      Handler: getImageById.lambdaHandler
      Runtime: nodejs10.x
      Description : ""
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::195957709288:role/lambda-dynamodb-access
      Environment:
        Variables: 
          BUCKET_NAME: jabara-serverless-app-photos
          TABLE_NAME : photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /image/{id}
            Method: GET
  deleteImageById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/
      Handler: deleteImageById.lambdaHandler
      Runtime: nodejs10.x
      Description : ""
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::195957709288:role/lambda-dynamodb-access
      Environment:
        Variables: 
          BUCKET_NAME: jabara-serverless-app-photos
          TABLE_NAME : photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /image/{id}
            Method: DELETE